# Generated by Django 4.2.10 on 2024-03-06 14:53

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_anime_alter_review_title_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
        migrations.AlterField(
            model_name='review',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
