# Generated by Django 4.2.10 on 2024-03-20 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0003_alter_comment_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="review_id",
            new_name="review",
        ),
        migrations.RenameField(
            model_name="comment",
            old_name="user_id",
            new_name="user",
        ),
    ]
