# Generated by Django 4.2.10 on 2024-03-06 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_anime_image_alter_review_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='public_id',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='review',
            name='public_id',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
