# Generated by Django 4.2.10 on 2024-03-22 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_rename_review_id_comment_review_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='updated_time',
        ),
    ]
